import type { Trade, Material, ScenarioFactors, SoftCost, EquipmentItem, CostCategory } from './types';

// Oklahoma Medical Staff Labor Rates 2025-2026 (Fully Burdened)
export const oklahomaLaborRates: Trade[] = [
  {
    name: 'Physician (General Practice)',
    hourlyRate2025: 95.00,
    hourlyRate2026: 99.75,
    burdenedRate: 147.25, // Includes malpractice insurance, benefits, taxes (~55% burden)
    efficiencyFactor: 0.02, // Hours per sq ft
    estimatedHours: 1000,
    totalCost: 147250,
  },
  {
    name: 'Physician (Specialist)',
    hourlyRate2025: 125.00,
    hourlyRate2026: 131.25,
    burdenedRate: 193.75,
    efficiencyFactor: 0.015,
    estimatedHours: 750,
    totalCost: 145313,
  },
  {
    name: 'Registered Nurse (RN)',
    hourlyRate2025: 38.50,
    hourlyRate2026: 40.43,
    burdenedRate: 59.68,
    efficiencyFactor: 0.04,
    estimatedHours: 2000,
    totalCost: 119360,
  },
  {
    name: 'Licensed Practical Nurse (LPN)',
    hourlyRate2025: 26.75,
    hourlyRate2026: 28.09,
    burdenedRate: 41.46,
    efficiencyFactor: 0.03,
    estimatedHours: 1500,
    totalCost: 62190,
  },
  {
    name: 'Medical Assistant',
    hourlyRate2025: 18.25,
    hourlyRate2026: 19.16,
    burdenedRate: 28.29,
    efficiencyFactor: 0.05,
    estimatedHours: 2500,
    totalCost: 70725,
  },
  {
    name: 'Radiology Technician',
    hourlyRate2025: 32.50,
    hourlyRate2026: 34.13,
    burdenedRate: 50.38,
    efficiencyFactor: 0.01,
    estimatedHours: 500,
    totalCost: 25190,
  },
  {
    name: 'Medical Lab Technician',
    hourlyRate2025: 28.00,
    hourlyRate2026: 29.40,
    burdenedRate: 43.40,
    efficiencyFactor: 0.015,
    estimatedHours: 750,
    totalCost: 32550,
  },
  {
    name: 'Receptionist / Front Desk',
    hourlyRate2025: 16.50,
    hourlyRate2026: 17.33,
    burdenedRate: 25.58,
    efficiencyFactor: 0.025,
    estimatedHours: 1250,
    totalCost: 31975,
  },
  {
    name: 'Medical Billing Specialist',
    hourlyRate2025: 22.00,
    hourlyRate2026: 23.10,
    burdenedRate: 34.10,
    efficiencyFactor: 0.02,
    estimatedHours: 1000,
    totalCost: 34100,
  },
  {
    name: 'Facility Manager',
    hourlyRate2025: 35.00,
    hourlyRate2026: 36.75,
    burdenedRate: 54.25,
    efficiencyFactor: 0.01,
    estimatedHours: 500,
    totalCost: 27125,
  },
];

// Medical Equipment & Systems
export const defaultEquipmentItems: EquipmentItem[] = [
  {
    id: 'eq-1',
    name: 'MRI Machine (1.5 Tesla)',
    vendor: 'Siemens Healthineers',
    itemType: 'Equipment Rental',
    rateType: 'Monthly',
    rate: 35000,
    duration: 60,
    totalCost: 2100000,
    notes: 'Includes installation, service contract, and training',
  },
  {
    id: 'eq-2',
    name: 'Digital X-Ray System',
    vendor: 'GE Healthcare',
    itemType: 'Equipment Rental',
    rateType: 'Monthly',
    rate: 4500,
    duration: 60,
    totalCost: 270000,
    notes: 'Full digital radiography system with PACS integration',
  },
  {
    id: 'eq-3',
    name: 'Ultrasound System (High-End)',
    vendor: 'Philips Healthcare',
    itemType: 'Equipment Rental',
    rateType: 'Monthly',
    rate: 3200,
    duration: 60,
    totalCost: 192000,
    notes: '4D imaging capability with multiple probes',
  },
  {
    id: 'eq-4',
    name: 'Medical Gas System (O2, N2O, Vacuum)',
    vendor: 'BeaconMedaes',
    itemType: 'Subcontractor',
    rateType: 'Lump Sum',
    rate: 185000,
    duration: 1,
    totalCost: 185000,
    notes: 'Complete medical gas piping, manifolds, and alarms',
  },
  {
    id: 'eq-5',
    name: 'Electronic Health Records (EHR) System',
    vendor: 'Epic Systems',
    itemType: 'Subcontractor',
    rateType: 'Lump Sum',
    rate: 250000,
    duration: 1,
    totalCost: 250000,
    notes: 'Software licensing, implementation, and staff training',
  },
  {
    id: 'eq-6',
    name: 'Exam Tables & Medical Furniture',
    vendor: 'Midmark Corporation',
    itemType: 'Other',
    rateType: 'Lump Sum',
    rate: 125000,
    duration: 1,
    totalCost: 125000,
    notes: '15 exam rooms fully furnished',
  },
  {
    id: 'eq-7',
    name: 'Sterilization Equipment',
    vendor: 'STERIS Corporation',
    itemType: 'Equipment Rental',
    rateType: 'Monthly',
    rate: 2800,
    duration: 60,
    totalCost: 168000,
    notes: 'Autoclaves and sterilization monitoring systems',
  },
];

// Detailed Medical Clinic Cost Categories
export const defaultCostCategories: CostCategory[] = [
  {
    id: 'cat-1',
    name: 'Site Work & Foundation',
    items: [
      {
        id: 'sw-1',
        description: 'Site Preparation & Grading',
        quantity: 50000,
        unit: 'SF',
        unitCost: 0.85,
        wasteFactor: 0.05,
        totalCost: 44625,
      },
      {
        id: 'sw-2',
        description: 'Parking Lot & Accessible Ramps',
        quantity: 15000,
        unit: 'SF',
        unitCost: 8.50,
        wasteFactor: 0.08,
        totalCost: 137700,
      },
      {
        id: 'sw-3',
        description: 'Foundation (Reinforced Concrete)',
        quantity: 1200,
        unit: 'CY',
        unitCost: 195,
        wasteFactor: 0.08,
        totalCost: 252720,
      },
    ],
    subtotal: 435045,
  },
  {
    id: 'cat-2',
    name: 'Shell & Structure',
    items: [
      {
        id: 'ss-1',
        description: 'Structural Steel Frame',
        quantity: 85,
        unit: 'TON',
        unitCost: 3200,
        wasteFactor: 0.05,
        totalCost: 285600,
      },
      {
        id: 'ss-2',
        description: 'Exterior Walls (Medical-Grade)',
        quantity: 8500,
        unit: 'SF',
        unitCost: 35.00,
        wasteFactor: 0.06,
        totalCost: 315350,
      },
      {
        id: 'ss-3',
        description: 'Roofing System',
        quantity: 50000,
        unit: 'SF',
        unitCost: 9.75,
        wasteFactor: 0.07,
        totalCost: 521813,
      },
      {
        id: 'ss-4',
        description: 'High-Performance Windows',
        quantity: 2500,
        unit: 'SF',
        unitCost: 95,
        wasteFactor: 0.03,
        totalCost: 244563,
      },
    ],
    subtotal: 1367326,
  },
  {
    id: 'cat-3',
    name: 'Interiors & Finishes',
    items: [
      {
        id: 'if-1',
        description: 'Medical-Grade Vinyl Flooring',
        quantity: 35000,
        unit: 'SF',
        unitCost: 8.50,
        wasteFactor: 0.08,
        totalCost: 321300,
      },
      {
        id: 'if-2',
        description: 'Antimicrobial Wall Finishes',
        quantity: 80000,
        unit: 'SF',
        unitCost: 4.25,
        wasteFactor: 0.10,
        totalCost: 374000,
      },
      {
        id: 'if-3',
        description: 'Acoustical Ceiling Tiles (Healthcare)',
        quantity: 45000,
        unit: 'SF',
        unitCost: 6.50,
        wasteFactor: 0.06,
        totalCost: 310050,
      },
      {
        id: 'if-4',
        description: 'Exam Room Doors (Solid Core)',
        quantity: 15,
        unit: 'EA',
        unitCost: 2800,
        wasteFactor: 0.02,
        totalCost: 42840,
      },
      {
        id: 'if-5',
        description: 'Waiting Room Seating',
        quantity: 45,
        unit: 'EA',
        unitCost: 650,
        wasteFactor: 0.03,
        totalCost: 30098,
      },
      {
        id: 'if-6',
        description: 'Cabinetry & Millwork',
        quantity: 1,
        unit: 'LS',
        unitCost: 125000,
        wasteFactor: 0.05,
        totalCost: 131250,
      },
    ],
    subtotal: 1209538,
  },
  {
    id: 'cat-4',
    name: 'MEP',
    items: [
      {
        id: 'mep-1',
        description: 'HVAC System (Medical-Grade HEPA)',
        quantity: 1,
        unit: 'LS',
        unitCost: 385000,
        wasteFactor: 0.05,
        totalCost: 404250,
      },
      {
        id: 'mep-2',
        description: 'Emergency Power Generator',
        quantity: 1,
        unit: 'EA',
        unitCost: 95000,
        wasteFactor: 0.03,
        totalCost: 97850,
      },
      {
        id: 'mep-3',
        description: 'Electrical Distribution & Panels',
        quantity: 1,
        unit: 'LS',
        unitCost: 225000,
        wasteFactor: 0.05,
        totalCost: 236250,
      },
      {
        id: 'mep-4',
        description: 'LED Lighting (Hospital-Grade)',
        quantity: 250,
        unit: 'EA',
        unitCost: 850,
        wasteFactor: 0.03,
        totalCost: 219125,
      },
      {
        id: 'mep-5',
        description: 'Plumbing (Medical Sinks & Fixtures)',
        quantity: 1,
        unit: 'LS',
        unitCost: 165000,
        wasteFactor: 0.08,
        totalCost: 178200,
      },
      {
        id: 'mep-6',
        description: 'Fire Suppression & Alarms',
        quantity: 1,
        unit: 'LS',
        unitCost: 125000,
        wasteFactor: 0.05,
        totalCost: 131250,
      },
      {
        id: 'mep-7',
        description: 'Data/Telecom Infrastructure',
        quantity: 1,
        unit: 'LS',
        unitCost: 95000,
        wasteFactor: 0.05,
        totalCost: 99750,
      },
    ],
    subtotal: 1366675,
  },
  {
    id: 'cat-5',
    name: 'Medical-Specific Systems',
    items: [
      {
        id: 'med-1',
        description: 'Emergency Department Build-Out',
        quantity: 3,
        unit: 'ROOM',
        unitCost: 85000,
        wasteFactor: 0.05,
        totalCost: 267750,
      },
      {
        id: 'med-2',
        description: 'Operating/Procedure Rooms',
        quantity: 2,
        unit: 'ROOM',
        unitCost: 195000,
        wasteFactor: 0.03,
        totalCost: 401700,
      },
      {
        id: 'med-3',
        description: 'Imaging Room (MRI Suite)',
        quantity: 1,
        unit: 'ROOM',
        unitCost: 425000,
        wasteFactor: 0.05,
        totalCost: 446250,
      },
      {
        id: 'med-4',
        description: 'X-Ray Rooms (Shielded)',
        quantity: 2,
        unit: 'ROOM',
        unitCost: 125000,
        wasteFactor: 0.04,
        totalCost: 260000,
      },
      {
        id: 'med-5',
        description: 'Laboratory Equipment & Casework',
        quantity: 1,
        unit: 'LS',
        unitCost: 175000,
        wasteFactor: 0.05,
        totalCost: 183750,
      },
      {
        id: 'med-6',
        description: 'Pharmacy & Medication Storage',
        quantity: 1,
        unit: 'LS',
        unitCost: 85000,
        wasteFactor: 0.03,
        totalCost: 87550,
      },
    ],
    subtotal: 1647000,
  },
];

// Sample Material Database
export const sampleMaterials: Material[] = [
  {
    sku: 'HD-2X4-8-SPF',
    itemName: '2x4x8 SPF Stud',
    vendor: 'Home Depot',
    unitPrice: 3.48,
    bulkDiscount: 15,
    leadTime: 3,
    quantity: 2000,
    unit: 'EA',
    category: 'Framing',
    wasteFactor: 0.10,
    liveApiLink: 'https://api.homedepot.com/products/HD-2X4-8-SPF',
  },
  {
    sku: 'LOW-CONC-80LB',
    itemName: 'Concrete Mix 80lb',
    vendor: 'Lowes',
    unitPrice: 4.98,
    bulkDiscount: 12,
    leadTime: 1,
    quantity: 500,
    unit: 'BAG',
    category: 'Concrete',
    wasteFactor: 0.05,
    liveApiLink: 'https://api.lowes.com/products/LOW-CONC-80LB',
  },
  {
    sku: 'HD-DRYWALL-4X8',
    itemName: 'Drywall 1/2" 4x8',
    vendor: 'Home Depot',
    unitPrice: 12.98,
    bulkDiscount: 10,
    leadTime: 2,
    quantity: 1200,
    unit: 'SHEET',
    category: 'Interior Finishes',
    wasteFactor: 0.12,
    liveApiLink: 'https://api.homedepot.com/products/HD-DRYWALL-4X8',
  },
  {
    sku: 'BUILD-HVAC-3TON',
    itemName: '3-Ton HVAC Unit',
    vendor: 'Build.com',
    unitPrice: 2845.00,
    bulkDiscount: 8,
    leadTime: 14,
    quantity: 12,
    unit: 'EA',
    category: 'MEP',
    wasteFactor: 0.02,
    liveApiLink: 'https://api.build.com/products/BUILD-HVAC-3TON',
  },
  {
    sku: 'LOW-ELEC-WIRE-250',
    itemName: '12/2 NM-B Wire 250ft',
    vendor: 'Lowes',
    unitPrice: 89.99,
    bulkDiscount: 10,
    leadTime: 5,
    quantity: 80,
    unit: 'ROLL',
    category: 'MEP',
    wasteFactor: 0.08,
    liveApiLink: 'https://api.lowes.com/products/LOW-ELEC-WIRE-250',
  },
  {
    sku: 'HD-PLYWOOD-3/4',
    itemName: '3/4" Plywood 4x8',
    vendor: 'Home Depot',
    unitPrice: 48.97,
    bulkDiscount: 12,
    leadTime: 3,
    quantity: 600,
    unit: 'SHEET',
    category: 'Framing',
    wasteFactor: 0.15,
    liveApiLink: 'https://api.homedepot.com/products/HD-PLYWOOD-3/4',
  },
];

// Scenario-based factors
export const scenarioFactors: Record<string, ScenarioFactors> = {
  optimistic: {
    contingency: 0.05, // 5%
    wasteFactor: 0.05,
    laborEfficiency: 1.10, // 10% better efficiency
    materialInflation: 0.02, // 2% inflation
  },
  realistic: {
    contingency: 0.10, // 10%
    wasteFactor: 0.10,
    laborEfficiency: 1.00, // baseline
    materialInflation: 0.045, // 4.5% inflation
  },
  pessimistic: {
    contingency: 0.18, // 18%
    wasteFactor: 0.15,
    laborEfficiency: 0.85, // 15% worse efficiency
    materialInflation: 0.08, // 8% inflation
  },
};

// Soft Costs
export const defaultSoftCosts: SoftCost[] = [
  { name: 'Permits & Fees', amount: 2.5, isPercentage: true },
  { name: 'Insurance', amount: 1.8, isPercentage: true },
  { name: 'Architectural/Engineering', amount: 5.0, isPercentage: true },
  { name: 'Legal & Closing', amount: 1.2, isPercentage: true },
  { name: 'Financing Costs', amount: 3.5, isPercentage: true },
  { name: 'Project Management', amount: 4.0, isPercentage: true },
];
